version: "3.7"
services:
    db:
        env_file:
            - .env.local
    api:
        image: yzia2000/project-api:dev
        env_file:
            - .env.local
        build:
            context: .
            target: base
        container_name: project-api-dev
        command: npm run dev
        volumes:
            - ./src:/app/src
            - ./package.json:/app/package.json
volumes:
    db:
