version: "3.7"
services:
    db:
        image: postgres:13-alpine
        container_name: db
        env_file:
            - .env.prod
        ports: 
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data
    api:
        image: yzia2000/project-api
        build:
            context: .
        container_name: project-api
        env_file:
            - .env.prod
        depends_on:
            - db
        ports:
            - '5000:5000'
volumes:
    db:
