version: "3.7"
services:
    db:
        image: postgres:13-alpine
        env_file:
            - .env.local
        container_name: db-dev
        ports: 
            - '5432:5432'
        volumes:
            - dbdata:/var/lib/postgresql/data/
            - ./dbscripts:/docker-entrypoint-initdb.d

    api:
        image: yzia2000/zims-classroom:dev
        env_file:
            - .env.local
        build:
            context: .
            target: base
        container_name: api-dev
        command: npm run dev
        volumes:
            - ./src:/app/src
            - ./package.json:/app/package.json
        depends_on:
            - db
        ports:
            - '5000:5000'

volumes:
    dbdata:
